[BE/FE] 카드/계좌 GET API 개발 & 페이지 구현
boostcamp-2020/Project16-B-Account-Book pull request #31
Opened 2020-11-30 08:45 UTC by Yejikwon

## ✅ 작업 내용
- [X] [BE] 카드/계좌 API 서비스 로직 구현
  - 가계부 번호와 userId를 보내면 사용자가 등록한 결제 수단과 결제 수단 별 사용한 금액을 리턴하는 API를 구현했습니다.
- [X] [FE] Sidebar 수정 
  - 767px 이상일 때는 Sidebar를 고정으로 두는 것이 좋을 것 같아 X 버튼을 누르면 <br/>
    sidebar가 사라지게 하는 기능을 삭제했습니다.
- [X] [FE] 등록한 카드정보 표시
  - 사용자별 등록한 카드 정보를 표시하기 위해 Container를 구현했습니다.
  - 카드정보 페이지 구현을 위한 PaymentForm, Item 페이지를 작성했습니다.
- [X] [FE] header title 변경
  - header title을 우리 팀에 맞게 변경했습니다.

## 🔨 변경 사항 (구현 사항)
- [X] `Numeral.js` 라이브러리 설치 
  - 천 단위 콤마 표시를 위해 Numeral.js 라이브러리를 설치했습니다.

## 📸 스크린샷 (Optional)
- ![image](https://user-images.githubusercontent.com/13073517/100587115-83a66180-3333-11eb-93a0-176b768f7c7c.png)
- ![image](https://user-images.githubusercontent.com/13073517/100587195-9882f500-3333-11eb-9aca-5a5bc61e9025.png)
- ![image](https://user-images.githubusercontent.com/13073517/100587273-b0f30f80-3333-11eb-8488-f20eb70afb83.png)

## 🔒 관련이슈 (Optional)
- #9 #29 #18

2020-11-30 11:46 UTC, gyim1345 requested changes
스키마 변경하시면 얘기 해주셔야해요 ㅠㅠ 다른거 다 터집니다 :sob:

2020-11-30 11:46 UTC, gyim1345 commented on client/webpack.config.js
> +      favicon: './public/favicon.ico',
:+1:

2020-11-30 11:46 UTC, gyim1345 commented on server/src/controller/payment.controller.js
> +      const paymentsList = await PaymentService.makePaymentsTemplate(
controller에서 서비스 두번 요청 하는게 조금 이상하네요

2020-11-30 11:46 UTC, gyim1345 commented on server/src/controller/payment.controller.js
> +      const paymentsList = await PaymentService.makePaymentsTemplate(
보통 business logic은 service layer에서 해요
controller은 그냥 맞는 service에 연결 시키고 그에 따른 response 를 돌려주는걸로 알고 있습니다.

2020-11-30 11:46 UTC, gyim1345 commented on server/src/model/transaction.model.js
> +  accountBookId: String,
혹시 string으로 바꾸신 이유가 있을까요?

2020-11-30 11:46 UTC, gyim1345 commented on server/src/route/payment.route.js
> +router.get('/:userId', paymentController.getPayments);
참고로 저희 프로젝트는 oauth 구현하면 저희가 userId를 보내는게 아니라 token의 정보를 추출해서 사용해요!

2020-11-30 11:46 UTC, gyim1345 commented on server/src/service/payment.service.js
> +    throw new Error('요청하신 사용자의 결제수단이 존재하지 않습니다.');
에러 처리는 한번 상의 해봐야 겠네요

서버에서 상세하게 써서 보내줄지 아니면 status 코드만 보내서 client 에서 처리 할지

2020-11-30 11:46 UTC, gyim1345 commented on server/src/service/payment.service.js
> +    for (let [index, payment] of paymentList.entries()) {
js에선 보통 함수형으로 써요! 반복문을 조금 더 간결하게 만들고 의미있게 만들어서 좋습니다.
함수형 쓰는건 어떨까요? 이 경우에는 reduce랑 find쓰시면 바로 해결 될것 같아요!
[자바스크립트 코딩의 기술](http://www.yes24.com/Product/Goods/85019231) 추천합니다

2020-11-30 11:46 UTC, gyim1345 commented on client/package.json
> +    "numeral": "^2.0.6",
천 단위 ","는 Number(숫자).toLocalString() 쓰면 해결 됩니다!

2020-11-30 11:46 UTC, gyim1345 commented on client/src/components/presentational/payment/PaymentItem.jsx
> +          {numeral(item.totalCost).format('0,0')}원
Number(숫자).toLocalString() !!

2020-11-30 13:04 UTC, Yejikwon commented on server/src/controller/payment.controller.js
> +      const paymentsList = await PaymentService.makePaymentsTemplate(
네넵 기봉님께서 말씀해주신 내용 구현한 상태입니다!

서비스는 한 번에 하나의 모델에 쿼리 요청을 해야하는 걸로 알고 있어서 
각각 필요한 내용이 달라 두 개로 나누게 되었습니다!
(서로 다른 컬렉션(UserModel, TransactionModel)에 있는 데이터들을 합쳐야해서 서비스를 나눌 수밖에 없었습니다~~)

`getPayments`: 로그인한 user가 등록한 결제 수단
`makePaymentsTemplate`: `getPayments`에서 받은 결제수단과 가계부 번호를 비교해서 결제수단 + 결제수단별 total 금액을 리턴해주는 템플릿

그래서,
최종적으로 controller에서 제가 얻고자했던 결제수단 별 결제금액과 결제수단 이름을 리턴해줍니다!

2020-11-30 13:06 UTC, Yejikwon commented on server/src/model/transaction.model.js
> +  accountBookId: String,
ㅠㅠㅠ 정말 죄송해요 ㅠㅠㅠ 
`ObjectId` 로 되어있을 때는 find 하면 데이터를 못찼아서
`String`으로 가계부 번호를 바꾸니 잘 찾아져서 바꾸게 되었습니다 ㅠㅠㅠㅠ

~~~
      const transactionList = await TransactionModel.find({
        accountBookId: accountBookId,
        paymentMethod: payment,
      });
~~~

내일 말씀드리고 다시 원상복구하거나 
의논해보고 String으로 바꿔도 되면 바꾸겠습니다 ㅠㅠㅠㅠㅠ

확인해주셔서 감사합니다 :)

2020-11-30 13:07 UTC, Yejikwon commented on server/src/route/payment.route.js
> +router.get('/:userId', paymentController.getPayments);
오오!!!!!! token 추출방식 좋습니다 :) 
지금은 테스트용으로 이렇게 받고, OAuth 구현되면 수정하겠습니다
감사합니다~!

2020-11-30 13:07 UTC, Yejikwon commented on server/src/service/payment.service.js
> +    for (let [index, payment] of paymentList.entries()) {
헛 감사합니다 ㅎㅎㅎ

2020-11-30 13:08 UTC, Yejikwon commented on client/package.json
> +    "numeral": "^2.0.6",
ㅎㅎㅎ감사합니다 기봉님~!
다음엔 저 녀석도 써보도록 하겠습니다!!
괜히 찾아봤네옄ㅋㅋㅋㅋㅋㅋ ㅎㅎㅎㅎㅎ

2020-12-01 01:16 UTC, gyim1345 commented on server/src/route/payment.route.js
> +router.post('/:userId', paymentController.getPayments);
혹시 post로 변경 하시고 params도 보내신 이유가 뭘까요?

2020-12-01 01:16 UTC, gyim1345 commented on server/src/service/payment.service.js
> +    const resultById = await UserModel.find({ _id: userId });
하나만 찾으실거면 findOne 쓰는것도 좋습니다
https://mongoosejs.com/docs/queries.html

2020-12-01 01:16 UTC, gyim1345 commented on client/src/components/presentational/common/Sidebar.jsx
>                <li key={'sidebar' + index} className={item.cName}>
혹시 이 class는 어디에 쓰이는건가요??

2020-12-01 01:16 UTC, gyim1345 commented on server/src/controller/payment.controller.js
> +      const paymentsList = await PaymentService.makePaymentsTemplate(
"서비스는 한 번에 하나의 모델에 쿼리 요청을 해야하는 걸로 알고 있어서" 라고 하셨는데 제가 아는거랑 조금 다르군요 ㅋㅋ
저는 "controller에서 하나의 service만 요청 한다" 로 알고 있습니다. 
제가 아는거랑 예지님이랑 아는거랑 둘다 만족 시키는 조건이 있습니다 ㅋㅋ
service 안에 두개의 private method를 만들어서 하나의 public method 에서 불러오는건 어떨까요?

2020-12-01 01:16 UTC, gyim1345 commented on server/src/controller/payment.controller.js
> +      const paymentsList = await PaymentService.makePaymentsTemplate(
https://velog.io/@hopsprings2/%EA%B2%AC%EA%B3%A0%ED%95%9C-node.js-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%95%84%ED%82%A4%ED%85%8D%EC%B3%90-%EC%84%A4%EA%B3%84%ED%95%98%EA%B8%B0

2020-12-01 01:16 UTC, gyim1345 commented on server/src/route/payment.route.js
> +router.get('/:userId', paymentController.getPayments);
정확히 말해서 미들웨어에서 token을 validate 후 그에 맞는 user 정보를 db에서 조회해서 request에 강제 주입 할 생각이였습니다 ㅋㅋ

2020-12-01 01:20 UTC, Yejikwon commented on client/src/components/presentational/common/Sidebar.jsx
>                <li key={'sidebar' + index} className={item.cName}>
nav-text <-- 요 걸로 클래스이름 만들어서 위에서 디자인에 쓰이고 있습니다 ㅎㅎㅎㅎ

2020-12-01 02:09 UTC, jch422 approved these changes
👍

2020-12-01 02:09 UTC, gyim1345 approved these changes
수고하셨습니다!

2020-12-01 02:10 UTC, merged